### ISSUE TITLE
Send multiple files

### ISSUE THREAD

**Issue by aslafy-z** [schollz/croc#101]
It would be great to be able to send multiple files at a time.

Eg:
```sh
croc file-1 file-2
```

On the other side:
```
Receiving file-1 (1 kB) into: file-1
Receiving file-2 (1 kB) into: file-2
ok? (y/N)
```

This project looks awesome, I'd be pleased to contribute to it later!

**Comment by schollz** [comment]
@aslafy-z How would you go about doing this?

There are a couple of options:

- Transfer files in parallel (doable, but the UI is a nightmare because it requires syncing the UIs)
- Zip the files first, and then send the zipped files (this is currently what croc does with directories)
- Receive the files one at a time, requiring individual confirmation for each, sequentially (the easiest option, but not very useful)

**Comment by Fastidious** [comment]
@schollz I say zipping the files would be the best approach.

**Comment by schollz** [comment]
@Fastidious In that case, what would be expected for the output folder? Should both files go to the same folder (usually current folder of croc, or whatever is specified with `--out`) or should they go to different relative directories?

**Comment by Fastidious** [comment]
@schollz wouldn't the output directory by that from which `croc` is run? For example, if someone sends me a file, and I open my iTerm, and go to `~/Downloads/` and run croc there, then the file will be  saved under `~/Downloads/`. Alternatively, perhaps having the ability to set a default "transfer" directory?

If the question is whether the zip will expand into one directory, with the two files in it, or two directories, each with each file, I would pick the first, any day.

**Comment by schollz** [comment]
@Fastidious Yes, by default *croc* would output the data into the directory that croc is run. However, there is a command-line flag `--out` where you can specify a different output directory.  There isn't a way to do this in the config file yet.

**Comment by muhazzz** [comment]
@Fastidious @schollz I'm sorry, but zipping files would be the WORST approach. Did you ever tried to zip and transfer something bigger than 30Gb? Database dump files, for example... You'll wait many hours only to make zip. It's way better to send all files unzipped, in parallel

**Comment by Fastidious** [comment]
@muhazzz I understand. If those files are already in a directory, the resultant ZIP file can already be huge, and take a long time to create. Perhaps using something other than **croc** for cases like these then? I am sure @schollz is open to suggestions. I don't think we will want to send all files unzipped.

**Comment by schollz** [comment]
@muhazzz Good point. One of the benefits for croc is that for files you can just send in place, without using up extra disk. One clarification though: croc probably shouldn't send files in parallel. It already tries to use the full-bandwidth to send a single file, and I don't see an advantage to split the bandwidth across multiple files rather than just sending them one at a time.

If the answer to this is just sending them one at a time, via the command line `croc send file1 file2 file3`, then I think it can be done now (https://github.com/schollz/croc/commit/068fdb77fc7146159d12a57fc2a7e7d466822615 fixed a problem that kept me from doing it before).

**Comment by muhazzz** [comment]
@schollz yes, in full-bandwidth case one at a time would be great.

**Comment by ashishmax31** [comment]
@schollz If this is not done already, can I take this up?

**Comment by schollz** [comment]
@ashishmax31 Its not done, and sure you can take it up.

I think this will be a breaking change because it will have to add another communication between sender and recipient. Since only the sender knows that there are multiple files, it will have to communicate that, e.g. after each file it should probably tell the recipient "there's another file, get ready".

**Comment by schollz** [comment]
This is working now in v6.0.0
