### ISSUE TITLE
Does all the data go thru the relay?

### ISSUE THREAD

**Issue by postacik** [schollz/croc#104]
Hi,
I could not understand the role of the relay in the whole picture.

Does all the data go through the relay or is it used only for communicating the necessary data for peer to peer connection?

Can you please explain?

**Comment by schollz** [comment]
Yes, all data goes through the relay. I haven't found a way that can reliably send data *directly* between two computers that don't have port-forwarding enabled.

*croc* differs from a utility like *scp* because it doesn't require any two computers to have enabled port-forwarding, nor does it require computers having any server setup. Instead, *croc* will uses a relay - a temporary server setup locally (if both computers are on lan) or publicly (default is at croc4.schollz.com). Any two computers can connect to the relay, and after securing their channel with PAKE, they can transfer encrypted metadata and data through the relay. The relay works by first having the computers communicate the PAKE protocol via websockets, and then exchanging encrypted metadata, and then stapling the TCP connections directly so that they can transfer directly.

**Comment by Fastidious** [comment]
@postacik from the croc readme file:
> The relay is needed to staple the parallel incoming and outgoing connections...
I am assuming that means all data goes through the relay.

**Comment by postacik** [comment]
I had thought that, maybe "magically" you had also implemented a working peer2peer communication behind all kinds of network topologies.

Anyway, thank you very much for the application and the explanation. 👍
