### ISSUE TITLE
Piping to stdout question

### ISSUE THREAD

**Issue by rubiojr** [schollz/croc#191]
Croc version: 6.4.8

:wave: I'm just trying to understand the design decision behind the `--stdout` behavior.

It seems that when using `--stdout` the data is written to disk first inside the current dir, then read and written to `stdout` when the transfer finishes. The temp copy is removed after that. Is that correct?

I was trying to pipe a large video to mplayer/mpv (`croc --stdout --yes <code> | mpv -cache 1024`) and realized that I'd have to wait for the full file to be downloaded first.

**Comment by Wouter0100** [comment]
This seems to be the case according to the [code](https://github.com/schollz/croc/blob/3c0371986315b915bc2f0b9ea0c3e20c07acccb4/src/croc/croc.go#L1119-L1135).

**Comment by schollz** [comment]
@rubiojr Yep, that's right. This is because when the multiplexing is used to transfer data, so the data are sent as individually compressed/encrypted "blocks" which may be out of order. When they are received they are written at the position specified.

It's already possible to turn off the multiplexing, and it wouldn't be hard to allow the file to be written in order (so you could skip the file creation) to get the functionality you need.

**Comment by rubiojr** [comment]
Ah I see. Thanks, that helps!
