### ISSUE TITLE
Output doesn't fit into terminal width

### ISSUE THREAD

**Issue by lpar** [schollz/croc#195]
**Describe the bug**
During a transfer, the progress bars scroll the terminal every time they print. I get a progress bar, then a blank line, then the next printing of the progress bar, and so on.

**To Reproduce**
Initiate a transfer in an 80 column terminal.

**Expected behavior**
I expected the progress bar to be sized or the filenames truncated so that the output would fit without scrolling, or fit in 80 columns if it's impossible to detect the terminal width.

**Version**
croc version v6.4.10-073569f

**Additional context**
Linux to Linux transfer. Haven't tested on macOS yet but could do so.

**Comment by schollz** [comment]
This is expected behavior - the output requires columns equal to the length of the longest filename plus the length of the progressbar. Thus, if you run and one of your filenames is super long, it will probably cause scrolling. This behavior is because I wanted to prioritize showing filenames over keeping inside the columns of the terminal.

**Comment by lpar** [comment]
OK. It just wasn't what I expected :-)
