### ISSUE TITLE
Mitigating a malicious relay or an eavesdropping attacker

### ISSUE THREAD

**Issue by anotherwon** [schollz/croc#200]
**Please try to [download the latest version](https://github.com/schollz/croc/releases/latest) of croc before reporting a bug!**

**Describe the bug**
Communication with the relay is completly unencrypted which includes the codephrase.
A malicious relay or an active attacker eavesdropping can therefore receive the senders' files.

**To Reproduce**
1. ./croc send file
2. Sniff network traffic for codephrase.
3. ./croc sniffed-code-phrase

**Expected behavior**
Communication with the relay is secured to prevent eavesdroppers from receiving my files.
Ideally, prevent a malicious relay from receiving my files.

**Version**
croc version v6.4.11-bc0841d

**Comment by schollz** [comment]
> Communication with the relay is completly unencrypted which includes the codephrase

This is a bit inaccurate. Let me try to explain things to clarify.

The "codephrase" is not really a code phrase in the sense it is used to encrypt the message. The codephrase is only used to navigate both users to the same place on the public relay. When both users enter the public relay (using the codephrase) they do PAKE. PAKE enables both users to generate a secure password that encrypts ALL further information (including information exchanged in the relay, and the file transfer).

Let me repeat that - the only "unencrypted" information is the codephrase (which is only used to navigate both users to the same public space, and never used for encryption) and the PAKE exchange ([which is a cryptographic procedure designed for two parties to **publicly** generate a secure key](https://github.com/schollz/pake)).

> A malicious relay or an active attacker eavesdropping can therefore receive the senders' files.

This is true. A malicious relay *could* receive the sender's files, or an attacker who is spamming codephrases (only a malicious relay which allows such a thing) could jump in to receive the file. **However, the sender will always know when their file was intercepted.** The secure key generated by PAKE ensures that *only two* parties can complete the process to generate the key, otherwise an error is generated and the transfer is aborted, which both the sender and recipient will see. If the malicious relay succeeds, then the sender will see their file transferred and the recipient will see nothing happen, so they know it was intercepted and they can alert the sender.

This also bears repeating - *the parties will always know if someone has intercepted the file*, even by a malicious relay.

So, what to do about a malicious relay?

The problem of a malicious relay is more of a problem of public trust. If you are using a public relay then there is trust needed. You need the same trust if you were to download the `croc` binary and run it on your computer. That being said, there are already two ways you can mitigate the level of trust:

1. Use the `--ask` flag in `croc` when sending. This will securely transfer the machine IDs between computers and double-check with the sender before actually sending the file. The sender can verify with your receipient that they are receiving the file. A malicious relay won't be able to replicate the recipients machine ID since that information is encrypted under PAKE and they don't have access to the recipients machine to know it.
2. Don't use a public relay. `croc` is open-source, as well as the relay. So you can run your own relay and use the `--pass` flag to password protect it, instead of trusting a public one.

**Comment by anotherwon** [comment]
> > Communication with the relay is completly unencrypted which includes the codephrase
> 
> This is a bit inaccurate. Let me try to explain things to clarify.
> 
> The "codephrase" is not really a code phrase in the sense it is used to encrypt the message. The codephrase is only used to navigate both users to the same place on the public relay. When both users enter the public relay (using the codephrase) they do PAKE. PAKE enables both users to generate a secure password that encrypts ALL further information (including information exchanged in the relay, and the file transfer).
> 
> Let me repeat that - the only "unencrypted" information is the codephrase (which is only used to navigate both users to the same public space, and never used for encryption) and the PAKE exchange ([which is a cryptographic procedure designed for two parties to **publicly** generate a secure key](https://github.com/schollz/pake)).

Agreed, I have been a bit inaccurate. However, so are you. ;)

The unencrypted information exchanged with the relay are at least:
* password for the relay
* ports of the relay
* IP and port as seen from the relay
* codephrase
* IP and port of the sender as seen from the sender (whether or not it makes sense to publish non-public IP addresses and the privacy implications thereof is another discussion)

> > A malicious relay or an active attacker eavesdropping can therefore receive the senders' files.
> 
> This is true. A malicious relay _could_ receive the sender's files, or an attacker who is spamming codephrases (only a malicious relay which allows such a thing) could jump in to receive the file. 

An attacker who can sniff the network does not need to spam.

> **However, the sender will always know when their file was intercepted.** The secure key generated by PAKE ensures that _only two_ parties can complete the process to generate the key, otherwise an error is generated and the transfer is aborted, which both the sender and recipient will see. If the malicious relay succeeds, then the sender will see their file transferred and the recipient will see nothing happen, so they know it was intercepted and they can alert the sender.
> 
> This also bears repeating - _the parties will always know if someone has intercepted the file_, even by a malicious relay.

That seems to be correct from what i can tell skimming the code.
However, preventing an attacker from receiving data in the first place is a more desirable goal, IMHO.

> The problem of a malicious relay is more of a problem of public trust. If you are using a public relay then there is trust needed. You need the same trust if you were to download the `croc` binary and run it on your computer. That being said, there are already two ways you can mitigate the level of trust:

The level of trust needing to be given to a public relay depends on the design choices.

>     1. Use the `--ask` flag in `croc` when sending. This will securely transfer the machine IDs between computers and double-check with the sender before actually sending the file. The sender can verify with your receipient that they are receiving the file. A malicious relay won't be able to replicate the recipients machine ID since that information is encrypted under PAKE and they don't have access to the recipients machine to know it.

Using the `--ask` flag does indeed require approval from the sender.
However, checking 32 alphanumeric characters is not "easy" or convenient. It is also not the default.

>     2. Don't use a public relay. `croc` is open-source, as well as the relay. So you can run your own relay and use the `--pass` flag to password protect it, instead of trusting a public one.

Running a private relay alone does not prevent a sniffing attacker.

So apparently the codephrase is mainly (only?) used for discovery and not for authentication.
Why not do what some other file sharing services nowadays do (with URI fragments) and append authentication information to the shared secret?
E.g. generate a longer codephrase and transmit only a prefix to the relay for discovery. Use the rest for authentication.

**Comment by schollz** [comment]
Okay, I'm on the same page now. 

I think you have a good idea here:

> Why not do what some other file sharing services nowadays do (with URI fragments) and append authentication information to the shared secret?

I'm not sure I fully understand this, can you elaborate? I'd really like a way to do this better, that is also more easy and convenient than checking the 32 characters from the `--ask` flag. But I'm not sure any authentication mechanism would allow you to know verify the identities of both parties without having both parties to check *something.*

> The unencrypted information exchanged with the relay are at least:
> password for the relay

Thank you for pointing this out. I can definitely fix this. I can also make sure that the codephrase can be encrypted so at least only the relay can decipher it. However, I'm not sure what can be done for encrypting the ports/ip of the connections.

**Comment by schollz** [comment]
Okay, all the communication between the relay and the user is can also encrypted using PAKE: https://github.com/schollz/croc/commit/d5846bc88da84d655c4b937db47ca103cc87d81a

**Comment by schollz** [comment]
External IP now is transmitted in an encrypted way between clients: https://github.com/schollz/croc/commit/5fce2a2e27768ac2a70c37b5fa00e6496b051876

**Comment by anotherwon** [comment]
> I'm not sure I fully understand this, can you elaborate? I'd really like a way to do this better, that is also more easy and convenient than checking the 32 characters from the `--ask` flag. But I'm not sure any authentication mechanism would allow you to know verify the identities of both parties without having both parties to check _something._

example: copy-lexicon-project-perform-delete-joker

To the relay both sender and receiver only transmit **copy-lexicon-project**.
Once an encrypted channel is established between sender and receiver, the receiver asks for the full codephrase **copy-lexicon-project-perform-delete-joker**.

That way the relay doesn't get to know the secret but only the discovery part.

E.g. Firefox Send does this with fragments attached to the URL. (See https://github.com/mozilla/send/blob/master/docs/encryption.md) Others do this as well.
Note: A fragment is not supposed to be send to the server but ["dereferenced solely by the user agent"](https://tools.ietf.org/html/rfc3986#section-3.5).

Unfortunately, didn't have time to test your patches, yet.

**Comment by schollz** [comment]
You're totally right, thats a good idea. I implemented it in https://github.com/schollz/croc/commit/8b6500adfd841ccf94bd914a384bfd9a966bec3e

Basically now only the first three characters establishes the channel. The rest is used with PAKE, so it is only successful if both parties have the full codephrase.

**Comment by DurandA** [comment]
Hi and thanks for the interesting discussion. I arrived here because I wanted to know how the relay channel was derived from the codephrase.

> Basically now only the first three characters establishes the channel. The rest is used with PAKE, so it is only successful if both parties have the full codephrase.

I was expecting a hash of the codephrase to be used as a channel identifier in the first place. Did you consider it? If yes, why did you discard it?

**Comment by schollz** [comment]
@DurandA Using a hash of the codephrase as a channel identifier would also work. In fact it might be just slightly better because its even harder to figure out the code phrase than giving it the first three letters. Everything else should be just about the same though.

**Comment by DurandA** [comment]
After some more thoughts, I think your solution is better. The default keyspace from `mnemonicode` is only 32 bits if I am not mistaken:
https://github.com/schollz/croc/blob/386f4ff958015079ff189ef15d0494b383936294/src/utils/utils.go#L129-L131

It would not be too hard for a motivated attacker to brute-force/build a rainbow table for the whole keyspace. With your solution, the PAKE has only 1 chance out of ~2^21 to succeed for an attacker that know the channel.

**Comment by schollz** [comment]
@DurandA Okay, if you find anything else let me know!
