### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by Snawoot** [schollz/croc#223]
**Describe the bug**

Got panic while sending 385 files (7.7 GB total):

```
panic: read <removed>: file already closed

goroutine 1796 [running]:
github.com/schollz/croc/v8/src/croc.(*Client).sendData(0xc000084a80, 0x0)
	/home/omnipotent/go/pkg/mod/github.com/schollz/croc/v8@v8.0.11/src/croc/croc.go:1247 +0x66a
created by github.com/schollz/croc/v8/src/croc.(*Client).updateState
	/home/omnipotent/go/pkg/mod/github.com/schollz/croc/v8@v8.0.11/src/croc/croc.go:1084 +0x34e
```

**To Reproduce**
I don't know reliable way to reproduce this.

**Expected behavior**
No panics.

**Version**
`croc version v8.0.11-78b6437`

**Additional context**

**Comment by schollz** [comment]
Do you know if any of these files were being written/opened during the transfer?

**Comment by Snawoot** [comment]
It's possible some files were open for reading by bittorrent client.

**Comment by schollz** [comment]
Multiple readers wouldn't be a problem I think. If any files get modified during the transfer this messes up everything because the client needs to know the size / etc. to tell the recipient how to allocate the file and check the hash. 

That particular panic was planned: https://github.com/schollz/croc/blob/master/src/croc/croc.go#L1247, but I'm not sure why it was encountered. I've never encountered it. I'll have to think about this - let me know if you encounter it again!
