### ISSUE TITLE
Using the terminal as a GUI

### ISSUE THREAD

**Issue by schollz** [schollz/croc#267]
The issue https://github.com/schollz/croc/issues/264 brought by @mig4ng reveals something very interesting, maybe worth pursuing.

Normally you type `croc <codephrase>` to receive a file using the `codephrase` but if you instead type `croc file1 (file2)` it will interpret those as files and try to send them.

What if this type of behavior occured when you just typed `croc`?

Currently it will give this prompt:

```
> croc
Enter receive code:
```

But, what I'm proposing is changing it to this:

```
> croc
Enter receive code or file(s):
```

At which case, in Windows, you can drag-and-drop file names into there.

The benefit here is that, on Windows, you can then simply just double-click on the binary file and send *or* receive, instead of only receive as it is now.

I think the change would be pretty minimal too - it would just reusing @theStack's recent changes (https://github.com/schollz/croc/pull/266) to allow them to run on the input when its received from the `Enter receive....` prompt.

@theStack or @mig4ng, would of either of you be interested in trying this?

**Comment by theStack** [comment]
Very interesting idea for sure!

Right now the input prompt is emitted in the `receive()` function, so to generalize it for both sending/receiving one had to take it outside into the app.Action function (that obviously handles arguments that don't match any of the commands), then dependend on the input (via the allStringsAreFiles test) call either `send()` or `receive()` with an extra prompt argument. Will take a look into it. A perfect opportunity for Diving deeper into go. 🚶 

From a user's perspective, the only drawback I could think of is if one wants to receive a file with this method but locally a file with the exact name of the code exists -- then croc would try to send that file. The probability of this happening is really low though.

**Comment by mig4ng** [comment]
I believe this would be very technical for the common user, it might confuse people, however it is a good idea to try and get feedback.

As is the workflow for non technical people seems to work really well:
- to send you drag and drop into croc
- to receive double click croc and type the code

Adding this workflow might confuse the users, I know the motivation behind it is good, and us as logical (engineers) tend to look at solutions that seem simple but are complicated for the non-technical user.

If it was my decision I would keep it as is for now and focus the extra effort on making a GUI that is simple instead of the terminal. Unfortunately non-technical people (and sometimes technical people as well) fear the terminal, even though it is extremely powerful and easy to grasp once the fear is lost.

**Comment by schollz** [comment]
> From a user's perspective, the only drawback I could think of is if one wants to receive a file with this method but locally a file with the exact name of the code exists -- then croc would try to send that file. The probability of this happening is really low though.

Agreed, this is too unlikely to warrant extra logic.

> This is something I think I would be most likely able to explain to any of my parents.

Haha, that's exactly my practical usage as well. 


I think its worth a shot. It will be interesting to see how easy it can be (I think you may have to press "Enter" after adding each file, but maybe there is a way around that). If its not easy, then its okay, just a little fun learning Go. I'm happy to do this, unless someone would like to try it out.

**Comment by mig4ng** [comment]
I explained this to my girlfriend and she was like: "Do I have to type the name of the file in the terminal? That seems hard..." and she is more tech-savvy than most. I also showed her this flow:

- to send you drag and drop into croc
- to receive double click croc and type the code

And she really enjoyed it, and really liked it (against her typical use of WeTransfer and similar).

Again I believe this would only confuse most non-technical people using croc and that it is almost a waste of time, the only reason it is not a waste of time however is that the person implementing this will learn a bit of Go and croc in the process.

In my opinion a easy to use GUI would be a better investment of time, I have a simple user interface in mind, if you would like I can share it and we can discuss if it seems user friendly and intuitive 😃

**Comment by mig4ng** [comment]
I drew this on the day and forgot to upload, here it is:
![croc_ui](https://user-images.githubusercontent.com/5817039/94295684-85316300-ff59-11ea-8a17-3478c418d4c3.jpg)

I am not an artist but I think it is enough to get an idea of a simple and intuitive user interface for croc.
@schollz and @theStack what do you think?

**Comment by theStack** [comment]
@mig4ng: I'm by far no GUI expert (I feel indeed most home at the command line and the type of programmer where the graphical user interface always ends up crappy for the average user 😆 ), but for what it's worth, looks very good to me! What would happen as soon as the files are dropped to the "send area" above? Is the receive code displayed in an extra message box or just displayed below in the "receive file" group? It would be important in any case that it can be easily copy/pasted I think.

**Comment by mig4ng** [comment]
Probably the best approach would be a small text box with a button to automatically copy to the clipboard. It could also replace the drag and drop area saying the code and informing the user that it is required to keep the window opened. Maybe a process bar?

> I feel indeed most home at the command line

I try ask and learn from non-technical people what their needs are, however I usually am the same, the command line is so much better once you get over the fear of it.

**Comment by erfan1383** [comment]
Well, I do have a minimalistic-ish GUI already written in python using PySide2 (can also use PyQt5). And for the terminal on windows, I use [Alacritty](https://github.com/alacritty/alacritty). By using pyinstaller, one can already distribute this GUI, but I guess it has far too many problems for now.
[link to FileBin](https://filebin.net/4kh1krrutmp9wnoc)

**Comment by asheraryam** [comment]
I tried making a GUI but since the `send` command does not return immediately (it waits for the transfer to start), I was unable to capture the output and show it in the GUI.

**Comment by Krinkle** [comment]
> As-is the workflow for non technical people seems to work really well:
> 
> * **to send you drag and drop into croc**
> * to receive double click croc and type the code
> 

Thanks for explaining this. I would not have been able to figure this out otherwise. 

I used the CLI from macOS a few times, and based on reading [Sending a file in 2017](https://schollz.com/software/sending-a-file/#croc) I assumed it would be accessible to someone on Windows without needing to use the command line, type an exe path, and pass parameters to it. And, after downloading it, I was indeed surprised that it was a standalone executable that works by simple double-click. But, it seems to support only receiving of files. I could not figure out for days how to let them send a file to me. I read all the docs about croc I could find, and read through several of @schollz articles mentioning croc, but could not figure out a way, apart from via the command-line and using `/path/to/crox.exe send`. I simply assumed the 2017 article must've assumed a GUI that perhaps no longer exists (based on other issues I read here). And I too felt like an interactive mode would be a natural next step to make croc accessible in both directions, but I ended up using magic-wormhole and [sneakypete81/wormhole-ui](https://github.com/sneakypete81/wormhole-ui/) for the time being, which worked for us.

Upon revisiting this issue I found the above comment, and yep, drag-and-drop works great! Noting that one has to drag onto the program icon, not into the program window after it has launched. This makes sense if you know how shell programs tend to work, but I just wasn't thinking with that mindset when I tried to use `croc.exe` on someone's Windows machine.

My only suggestion would be to document this critical piece of information in a bunch of places. In the README, and perhaps in [the article](https://schollz.com/software/sending-a-file/#croc), or in the command-line output itself so that it is naturally discoverable at the last mile before the user might give up. Eg. it could launch as follows:

```
> croc
Croc is in receive mode. To send files, drag-and-drop files onto the croc program icon.

Enter receive code:
```

This might forgo most need for a GUI. It would still be _nice_ of course, but there'd be far fewer people giving up before they realise the awesomeness that croc has to offer!

If you're open to adding a message like the above, I could give that a try. I haven't worked with Go before, so this would be a good excuse for me to figure that out. The main hurdle I foresee is that the kind of text that I suspect would be most useful in standalone mode, is also likely to be confusing when running croc as a CLI program. I don't know if the current code structure and/or Go in general, make it easy to distinguish between the two?

**Comment by taotien** [comment]
I never knew I could just drop onto the icon, I've always instructed my friends to open up a shell in the folder, then type `croc send ` and drop the file into the window.

**Comment by LSChyi** [comment]
I have an idea, how about building another binary called `croc-interactive`, which can be run via double-click the icon from your mouse. The goal of this `croc-interactive`  is to collect the input parameters with a nice terminal interactive interface then run the croc, so that users not familiar with the terminal can use it happily.

The interactive interface could use such as `(tview)[https://github.com/rivo/tview]` with loading the same configurations as the `--remember` option to provide some default values.
