### ISSUE TITLE
To bring to your notice

### ISSUE THREAD

**Issue by vinaykamidi** [schollz/croc#298]
Hi, I wanted to bring to your notice that on linux installing croc with **snap** is buggy. It does not allow you to send text and is in general very slow. That being said installing it as a **deb package** works like a charm.

**Comment by schollz** [comment]
Yes, its known. snap does not work well: https://github.com/schollz/croc/issues/190#issuecomment-628696061

snap does not like dot-files / things outside $HOME and there isn't really a way around this due to how snap sandboxes. I've contacted snap forums about this and they basically said I should have [croc alert snap users about using snap](https://forum.snapcraft.io/t/croc-needs-permission-for-dotfiles-in-home/17424/10) which seems silly to me.
