### ISSUE TITLE
Receiveing did not work

### ISSUE THREAD

**Issue by Ygarr** [schollz/croc#371]
(sending)croc version v9.0.0-0c2089b

(receiving)croc version v8.6.12-c373b38

```
croc                                                                        
Enter receive code: 7405-silicon-palma-toast
connecting...2021/04/19 21:32:23 could not connect to 142.93.177.120:9009: read tcp 192.168.xxx.xxx:56082->142.93.177.120:9009: read: connection reset by peer
```

**Comment by schollz** [comment]
v9 is not backwards compatible.

v8 has no public relay available as it has a vulnerability.

Try upgrading your receiver.

**Comment by klm127** [comment]
Is it the case that the F-droid croc repo is an old version? https://f-droid.org/en/packages/com.github.howeyc.crocgui/

Fdroid app was updated 6 days ago, but I'm having the same issue with the device using the F-droid app and computer on v9

**Comment by schollz** [comment]
Yeah, that needs to be updated. I already made a PR (https://github.com/howeyc/crocgui/pull/16)

**Comment by Ygarr** [comment]
Arch linux also old version.
Windows version is fresh

**Comment by Alfavio** [comment]
@Ygarr [Arch Linux](https://archlinux.org/packages/community/x86_64/croc/) has the current version now.

**Comment by bentolor** [comment]
I stumbled over the same issue and think the error message is deceiving and requires deep technical competency to fix. 
I had hoped `croc` could be a "Dad-safe do this and I get/send you safely a file" option. Not yet it seems.

In my case the root cause is the outdated snap-Version :-/

@schollz Did you thought about implementing a version check which could indicate a version incompatibility? 
This could help to support a _Just works™_ experience…

**Comment by schollz** [comment]
I'd accept a PR for that
