### ISSUE TITLE
croc prompt refuses files when answering yes

### ISSUE THREAD

**Issue by shaicoleman** [schollz/croc#400]
## Describe the bug

croc prompt refuses files when answering yes

## To Reproduce

Answer **yes** when receiving a file

Accept 'myfilename' (12.3 kB)? (y/n) **yes**
2021/06/09 11:48:49 refused files

## Expected behaviour

* If the input is not understood or the input is blank, it should prompt again rather than reject the file
* yes/no should also be accepted as valid responses

## Version

`croc version v9.1.4-d0ebb7a`

**Comment by nikoksr** [comment]
@shaicoleman thanks for the report! 

@schollz I would like to take this one. I have an alternative suggestion tho. In the *nix world it is relatively common to specify a default option which is used on empty input.

Instead of this:
`Accept 'myfilename' (12.3 kB)? (y/n)`

it would look like this:
`Accept 'myfilename' (12.3 kB)? (Y/n)`

The capital `Y` implies that *yes* is the default answer. So to accept files, you could just press `Enter` or enter the letter `y` as usual. Its basically a small quality-of-life feature. Of course, we can also choose reject as default.

What do you think? Should I implement it this way, or ask again whenever the answer is not *y* or *n*, as @shaicoleman suggested.

**Comment by schollz** [comment]
@nikoksr I would love it if you wanted to PR this! I think that makes sense - yes as default.

**Comment by nikoksr** [comment]
@schollz Okay, then I make *yes* the default. 

What about the case that an invalid character is given, for example `b`. Cancel (as currently) or ask again for (Y/n)?

The advantage of asking again is, of course, that the sender doesn't have to send again just because you mistyped. But this is of course a bigger change in the code than just checking for blanks.

What would you prefer?

**Comment by schollz** [comment]
I think it should probably reject on any characters except "Y","y","yes","Yes","YES", etc.

**Comment by shaicoleman** [comment]
Please ask again if it's not a valid option, otherwise a typo requires the sender to resend which is an unnecessary hassle for a typo

**Comment by nikoksr** [comment]
@shaicoleman If we allow to press `Enter` to accept, it should hardly happen that you mistype. Sure, not everyone knows this, so they're likely to type text and potentially mistype, but I'm not sure it's worth looping queries for these rare scenarios.

We could add a note somewhere to alert users that from now on you can just press `Enter` to continue, be it in the CLI or just in the Readme.

At the end of the day, that's your decision @schollz.

**Comment by nikoksr** [comment]
I have now already opened the PR (#401). Should the prompt loop still be desired, I can easily add it.
