### ISSUE TITLE
room not ready

### ISSUE THREAD

**Issue by pablodz** [schollz/croc#499]
## Describe the bug 

room not ready being present when file is not found to send

## To Reproduce

1. Create dir, add files
2. Try to send a file that don't exists
3. Error appears

## Expected behaviour 

Error log that says that file was not found

## Version 

croc version v9.6.0-0e93f1e

**Comment by pablodz** [comment]
![Screenshot from 2022-08-12 13-39-36](https://user-images.githubusercontent.com/28235457/184422935-94baa6b8-6832-439e-9cd9-2fe82213a5da.png)

**Comment by schollz** [comment]
This *is* expected behavior. 

If you are trying to send a file the canonical command is `croc send <file>`.

If you accidentally leave off `send` and the `<file>` does exist, then croc will prompt you for what it thinks your trying to do. I.e., `croc <file>` *only* works if the file exists. If the file doesn't exist, then it does what it normally does and assumes that `<file>` is the passcode that was set.

**Comment by pablodz** [comment]
![Screenshot from 2022-08-12 14-00-13](https://user-images.githubusercontent.com/28235457/184425864-7ae7afd5-0e3f-4da1-9813-e25dea44efd5.png)

Oh, so, it's expected output, I'll close the issue, thanks for fast answer
