### ISSUE TITLE
Question about the local argument

### ISSUE THREAD

**Issue by beh-10257** [schollz/croc#503]
Is a wifi connection with or without internet considered a local network 
Cause when i do the local option with croc it doesn't discover anything no matter if i did it with the hotspot of my phone or with another phone
The version in both termux in my phone and in powershell windows is 9.6.0-0e93f1e

**Comment by lukas-mertens** [comment]
I am not completely sure about this, but I discovered that the sender has to be able to open ports, otherwise it tries to use the public relay, which obiously doesn't work without internet. [Here](https://github.com/schollz/croc/issues/441#issuecomment-1372054603) I went into more detail about this. So make sure that no firewall in your local network prevents the two clients from communicating directly to eachother and the sender opening a local relay.

**Comment by beh-10257** [comment]
stale boys are stupid peace
