### ISSUE TITLE
long running croc instances lose connection to relay

### ISSUE THREAD

**Issue by raimocom** [schollz/croc#783]
Yesterday i startet a **croc send** instance:
`croc --relay my.private.relay  send --code MY-TRANSFER-CODE bigFile.zip)`

Immediately after that i checked if the transfer works correctly on another system:
`croc --relay my.private.relay --yes --overwrite MY-TRANSFER-CODE`
which it did, yay! 

I then restarted the **croc send** for it to be ready for the actual transfer of that file today.
`croc --relay my.private.relay  send --code MY-TRANSFER-CODE bigFile.zip)`

Today i tried to receive the file. Again via:
`croc --relay my.private.relay --yes --overwrite MY-TRANSFER-CODE`

But this time i got an error
**_securing channel...2024/08/15 11:00:15 room (secure channel) not ready, maybe peer disconnected)_**

I checked the system on which the **croc send** ran. croc was still running, waiting to send data.

I then restarted croc:
`croc --relay my.private.relay  send --code MY-TRANSFER-CODE bigFile.zip)`

Then immediately afterward i retried to receive the file
`croc --relay my.private.relay --yes --overwrite MY-TRANSFER-CODE`
which worked fine.

Apparently there is no mechanism built into croc to keep the relay connection alive and handles relay reconnnection. Or it is not working as intended. Both sides used croc v10.

**Comment by schollz** [comment]
reusing transfer codes sometimes does that, if they were cancelled then it doesn't immediately delete the room I think. does it work if you use different transfer codes?

**Comment by cheese528** [comment]
Hi, I just want to follow-up with what @raimocom wrote.  The issue here is when a "croc send" is started, but the receiver doesn't immediately start receiving, after some time, the session will become invalid.  I have encountered this issue before as well.  

Let's say I start a 'croc send' session, and then the person on the receiving side waits till the next day to run 'croc' to receive the file, the session will fail with the error message as described by @raimocom.
